name: SWE Docs Artifacts

on: 
  push:
    branches:
      - main
    paths:
      - 'Esterni/**'
      - 'Interni/**'
      - 'Stile/**'
      - '.github/**'

jobs:
  artifacts:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v1
      # with:
      #  ref: develop
    
    - name: Search and Compiling Latex Files
      uses: Maxelweb/Latex-multicompiler@master
      with:
        path_to_list: .github/filesToCompile
        artifact: true

    #rif. uses: Jatus93/Latex-multicompiler@v1.0
    
    #- name: FTP Artifacts Online Deploy
    #  uses: SamKirkland/FTP-Deploy-Action@2.0.0
    #  env:
    #    FTP_SERVER: ${{ secrets.FTP_HOST }}
    #    FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
    #    FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    #    LOCAL_DIR: Documents
    #    ARGS: --transfer-all
