# This is a basic workflow to help you get started with Actions

name: Artifacts

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      matrix:
        include:
          - working_directory: Interni/StudioDiFattibilità
            root_file: "StudioDiFattibilità"
          - working_directory: Interni/Verbali Interni
            root_file: "VI_*"
 
            

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Find file
        id: file
        working-directory: ${{ matrix.working_directory }}
        run:  echo "##[set-output name=file;]$(basename `ls | egrep -R ${{ matrix.root_file }}` .tex)"

      # Runs a single command using the runners shell
      - name: Tex to PDF
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ${{ matrix.working_directory }}
          root_file: ${{ steps.file.outputs.file }}.tex
          post_compile: "latexmk -c"
          latexmk_shell_escape: true

      # Runs a set of commands using the runners shell
      - uses: actions/upload-artifact@v2
        with:
          name: RR
          path: |
            ${{ github.workspace }}/**/*.pdf
